# Add this to the top of the Podfile if it's missing
flutter_application_path = '../..'
load File.join(flutter_application_path, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

platform :ios, '13.0'  # Make sure the platform version is set correctly

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter Pods
  install_all_flutter_pods(flutter_application_path)
end
