# ios/fastlane/Fastfile
default_platform(:ios)

platform :ios do
  desc "Build and upload to Firebase App Distribution"
  lane :beta do
    # Ensure fastlane is installed in the environment
    match(type: "appstore")  # Optional, if you want to handle code signing with match
    build_app(scheme: "Runner")
    firebase_app_distribution(
      app: ENV["IOS_APP_ID"],
      token: ENV["TOKEN"],
      groups: "pre-tester",
      ipa_path: "./build/ios/iphoneos/Runner.ipa"
    )
  end
end
