platform :ios do
  desc "My awesome app"
  lane :distribute do
      build_ios_app(...)
      # build_ios_app is a built-in fastlane action.

      release = firebase_app_distribution(
          app: "1:123456789:ios:abcd1234",
          testers: "tester1@company.com, tester2@company.com",
          release_notes: "Lots of amazing new features to test out!"
      )

  end
end