name: Build & Upload to Firebase App Distribution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Java (required for Gradle)
      - name: Set Up Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

      # Set up Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Install Flutter dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Build APK (Android)
      - name: Build APK
        run: flutter build apk --release

      # Upload APK to Firebase App Distribution (Android)
      - name: Upload APK to Firebase App Distribution (Android)
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{ secrets.APP_ID }}
            token: ${{ secrets.TOKEN }}
            groups: pre-tester
            file: build/app/outputs/apk/release/app-release.apk

  ios_build:
    # Use macOS for iOS build
    runs-on: macOS-latest

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Decode google-services.json (optional for iOS)
      - name: Decode google-services.json
        env: 
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > ios/Runner/google-services.json

      # Decode firebase_options.dart (optional for iOS)
      - name: Decode firebase_options.dart
        env:
          FIREBASE_OPTIONS_DART: ${{ secrets.FIREBASE_OPTION }}
        run: echo "$FIREBASE_OPTIONS_DART" > lib/firebase_options.dart

      # Install Flutter dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Run Flutter Analyze (optional but recommended)
      - name: Run Flutter Analyze
        run: flutter analyze
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
      # Build iOS App
      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      # Upload iOS IPA to Firebase App Distribution
      - name: Upload IPA to Firebase App Distribution (iOS)
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{ secrets.IOS_APP_ID }}
            token: ${{ secrets.TOKEN }}
            groups: pre-tester
            file: ios/build/ios/iphoneos/Runner.ipa
