name: Build & Upload to Firebase App Distribution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Java (required for Gradle)
      - name: Set Up Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

      # Set up Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Install Fastlane
      - name: Set up Fastlane
        run: |
          sudo gem install fastlane -NV

      # Decode google-services.json
      - name: Decode google-services.json
        env: 
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      # Decode firebase_options.dart
      - name: Decode firebase_options.dart
        env:
          FIREBASE_OPTIONS_DART: ${{ secrets.FIREBASE_OPTION }}
        run: echo "$FIREBASE_OPTIONS_DART" > lib/firebase_options.dart

      # Install Flutter dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Run Flutter Analyze (optional but recommended)
      - name: Run Flutter Analyze
        run: flutter analyze

      # Build APK (Android)
      - name: Build APK
        run: flutter build apk --release

      # Run Fastlane for iOS build and upload to Firebase App Distribution
      - name: Build and Upload iOS App using Fastlane
        run: |
          cd ios
          fastlane beta
        env:
          IOS_APP_ID: ${{ secrets.IOS_APP_ID }}
          TOKEN: ${{ secrets.TOKEN }}

      # Upload APK to Firebase App Distribution (Android)
      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{ secrets.APP_ID }}
            token: ${{ secrets.TOKEN }}
            groups: pre-tester
            file: build/app/outputs/apk/release/app-release.apk
